// Mock product data — Crave Corner sweets only
export const products = [
  {
    id: 1,
    name: 'Molten Chocolate Lava Cake',
    description: 'A decadent individual chocolate cake with a warm, flowing molten center. Served warm with a dusting of powdered sugar and a scoop of vanilla bean ice cream.',
    price: 12.99,
    image: '/img/dish12.jpeg',
    category: 'cakes',
    categoryLabel: 'Cakes',
    rating: 4.9,
    reviews: 128,
    stock: 15,
    featured: true,
    badge: 'Bestseller',
    tags: ['chocolate', 'warm', 'decadent'],
  },
  {
    id: 2,
    name: 'Orange Cream Cupcakes',
    description: 'Light and fluffy orange-infused cupcakes crowned with silky cream cheese frosting and a candied orange zest garnish. A citrus dream in every bite.',
    price: 3.99,
    image: '/img/dish14.jpeg',
    category: 'cupcakes',
    categoryLabel: 'Cupcakes',
    rating: 4.7,
    reviews: 94,
    stock: 30,
    featured: true,
    badge: 'Popular',
    tags: ['citrus', 'light', 'frosted'],
  },
  {
    id: 3,
    name: 'Lemon Frosted Cookies',
    description: 'Buttery shortbread cookies kissed with fresh lemon zest, topped with a glossy lemon royal icing. Crisp edges, soft center — absolutely irresistible.',
    price: 2.49,
    image: '/img/dish15.jpeg',
    category: 'cookies',
    categoryLabel: 'Cookies',
    rating: 4.6,
    reviews: 73,
    stock: 50,
    featured: false,
    badge: null,
    tags: ['lemon', 'buttery', 'crispy'],
  },
  {
    id: 4,
    name: 'Matcha Cheesecake',
    description: 'A velvety Japanese matcha cheesecake with a buttery graham cracker crust, swirled with ceremonial-grade matcha and topped with white chocolate ganache.',
    price: 38.99,
    image: '/img/dish5.jpeg',
    category: 'cakes',
    categoryLabel: 'Cakes',
    rating: 4.8,
    reviews: 56,
    stock: 8,
    featured: true,
    badge: 'New',
    tags: ['matcha', 'japanese', 'creamy'],
  },
  {
    id: 5,
    name: 'Decadent Chocolate Mousse',
    description: 'Airy, silken dark chocolate mousse layered with fresh raspberries and whipped cream in an elegant glass. A Parisian classic reimagined for the modern palate.',
    price: 8.99,
    image: '/img/featured2.jpg',
    category: 'puddings',
    categoryLabel: 'Puddings & Mousse',
    rating: 4.9,
    reviews: 112,
    stock: 20,
    featured: true,
    badge: 'Bestseller',
    tags: ['chocolate', 'airy', 'elegant'],
  },
  {
    id: 6,
    name: 'Berry Bliss Smoothie Bowl',
    description: 'A vibrant frozen smoothie base of acai and mixed berries topped with granola, fresh strawberries, blueberries, banana slices, and a drizzle of raw honey.',
    price: 9.49,
    image: '/img/featured4.jpg',
    category: 'puddings',
    categoryLabel: 'Puddings & Mousse',
    rating: 4.5,
    reviews: 67,
    stock: 25,
    featured: false,
    badge: 'Healthy',
    tags: ['berries', 'fresh', 'healthy'],
  },
  {
    id: 7,
    name: 'Chocolate Chip Loaf',
    description: 'Moist, tender banana chocolate chip loaf cake made with ripe bananas and premium dark chocolate chips. Perfect sliced warm with a cup of tea.',
    price: 16.99,
    image: '/img/dish13.jpeg',
    category: 'cakes',
    categoryLabel: 'Cakes',
    rating: 4.6,
    reviews: 89,
    stock: 12,
    featured: false,
    badge: null,
    tags: ['banana', 'chocolate', 'loaf'],
  },
  {
    id: 8,
    name: 'Lemon Loaf Cake',
    description: 'Golden, perfectly moist lemon loaf glazed with a tart lemon drizzle icing. Made with fresh lemon juice and zest for a bright, sunshine-in-every-slice flavor.',
    price: 14.99,
    image: '/img/dish18.jpg',
    category: 'cakes',
    categoryLabel: 'Cakes',
    rating: 4.7,
    reviews: 103,
    stock: 10,
    featured: false,
    badge: null,
    tags: ['lemon', 'glazed', 'moist'],
  },
  {
    id: 9,
    name: 'Cinnamon Crumble Cookies',
    description: 'Rich espresso-infused cookies loaded with warming cinnamon and topped with a buttery brown sugar crumble. A coffee lover\'s perfect afternoon companion.',
    price: 2.99,
    image: '/img/dish17.jpg',
    category: 'cookies',
    categoryLabel: 'Cookies',
    rating: 4.8,
    reviews: 81,
    stock: 40,
    featured: true,
    badge: 'Fan Favorite',
    tags: ['coffee', 'cinnamon', 'crumble'],
  },
  {
    id: 10,
    name: 'Brioche French Toast',
    description: 'Thick-cut brioche French toast soaked in a vanilla custard, pan-fried to golden perfection, and served with fresh berries, maple syrup, and whipped cream.',
    price: 11.49,
    image: '/img/dish35.jpg',
    category: 'puddings',
    categoryLabel: 'Puddings & Mousse',
    rating: 4.6,
    reviews: 58,
    stock: 18,
    featured: false,
    badge: null,
    tags: ['brioche', 'vanilla', 'breakfast'],
  },
  {
    id: 11,
    name: 'Nigerian Puff Puff',
    description: 'Soft, airy West African deep-fried dough balls lightly spiced with nutmeg and vanilla. Perfectly golden on the outside, cloud-like on the inside. A nostalgic treat.',
    price: 5.99,
    image: '/img/dish20.jpg',
    category: 'cupcakes',
    categoryLabel: 'Cupcakes',
    rating: 4.9,
    reviews: 145,
    stock: 60,
    featured: true,
    badge: 'Cultural Gem',
    tags: ['african', 'fried', 'nostalgic'],
  },
  {
    id: 12,
    name: 'Chocolate Peanut Butter Loaf',
    description: 'An indulgent marriage of rich dark chocolate and creamy peanut butter in a moist, fudgy loaf. Topped with a glossy peanut butter drizzle and crushed peanuts.',
    price: 17.99,
    image: '/img/dish19.jpg',
    category: 'cakes',
    categoryLabel: 'Cakes',
    rating: 4.8,
    reviews: 76,
    stock: 9,
    featured: false,
    badge: null,
    tags: ['chocolate', 'peanut butter', 'loaf'],
  },
  {
    id: 13,
    name: 'Rose & Pistachio Macarons',
    description: 'Delicate French macarons with crispy shells and chewy centres, filled with rose buttercream and crushed Sicilian pistachios. Elegant, floral, and utterly luxurious.',
    price: 4.49,
    image: '/img/dish16.jpeg',
    category: 'cookies',
    categoryLabel: 'Cookies',
    rating: 4.7,
    reviews: 92,
    stock: 35,
    featured: true,
    badge: 'Luxury',
    tags: ['rose', 'pistachio', 'french'],
  },
  {
    id: 14,
    name: 'Vanilla Bean Crème Brûlée',
    description: 'Classic French custard infused with authentic Madagascar vanilla beans, finished with a perfectly caramelised sugar crust. Rich, silky, and utterly sophisticated.',
    price: 9.99,
    image: '/img/dish21.jpg',
    category: 'puddings',
    categoryLabel: 'Puddings & Mousse',
    rating: 4.9,
    reviews: 134,
    stock: 15,
    featured: true,
    badge: 'Bestseller',
    tags: ['vanilla', 'french', 'custard'],
  },
  {
    id: 15,
    name: 'Strawberry Shortcake',
    description: 'Layers of feather-light vanilla sponge, fresh whipped cream, and macerated strawberries. A timeless classic that celebrates the very best of summer.',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop&q=80',
    category: 'cakes',
    categoryLabel: 'Cakes',
    rating: 4.8,
    reviews: 108,
    stock: 6,
    featured: true,
    badge: 'Seasonal',
    tags: ['strawberry', 'cream', 'sponge'],
  },
  {
    id: 16,
    name: 'Coca-Cola Chocolate Cake',
    description: 'Moist, rich chocolate cake made with Coca-Cola for a unique, tangy flavor. Topped with a decadent Coca-Cola chocolate frosting.',
    price: 54.99,
    image: '/img/dish23.jpg',
    category: 'cakes',
    categoryLabel: 'Cakes',
    rating: 4.8,
    reviews: 108,
    stock: 6,
    featured: false,
    badge: null,
    tags: ['coca-cola', 'chocolate', 'cake'],
  },
];

export const getFeaturedProducts = () => products.filter(p => p.featured);
export const getProductsByCategory = (category) =>
  category === 'all' ? products : products.filter(p => p.category === category);
export const getProductById = (id) => products.find(p => p.id === parseInt(id));
